---
name: immune-lint
runs:
  using: composite
  steps:
    - name: Checkout immune-lint script
      uses: actions/checkout@v4
      with:
        repository: mikieto/jibun-os
        ref: main
        path: .tmp-jibun-os
        sparse-checkout: |
          scripts/
          legislation/common/quality_gate.yaml
        sparse-checkout-cone-mode: false
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v5
      with: {python-version: '3.11'}
    - name: Install dependencies
      run: pip install pyyaml python-dateutil
      shell: bash
    - name: Run immune-lint
      run: |
        python .tmp-jibun-os/scripts/immune_lint.py \
          --gate ".tmp-jibun-os/legislation/common/quality_gate.yaml"
      shell: bash
