---
schema:
  jibun-os.yml: schema/jibun-os.schema.json
extends: default
rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: consistent
    indent-sequences: true
  braces: enable
  brackets: enable
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
  new-line-at-end-of-file: enable
  truthy: disable
