#  毎日 02:00 JST（= 17:00 UTC）に台帳を自動再生成して PR
name: Collect Ledgers
on:
  schedule:
    - cron: '0 17 * * *'     # 17:00 UTC = 02:00 JST
  workflow_dispatch: {}      # 手動実行も可

permissions:
  contents: write            # bot でコミットするため
  pull-requests: write

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GIT_AUTHOR_NAME: mikieto
      GIT_AUTHOR_EMAIL: noreply@users.noreply.github.com
      GIT_COMMITTER_NAME: mikieto
      GIT_COMMITTER_EMAIL: noreply@users.noreply.github.com
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # ---------- 1) Python 実行で最新ログを生成 ----------
      - name: Generate ledgers
        run: python scripts/generate_ledgers.py
        shell: bash

      # ---------- 2) 変更があれば自動 PR ----------
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore(records): nightly ledger auto-update'
          branch: bot/ledger-update-${{ github.run_id }}
          title: 'chore(records): nightly ledger auto-update'
          body: |
            自動収集スクリプトが生成した台帳を反映します。
            - 自動生成日時 (JST): ${{ env.TZ }}
            - 確認後、マージしてください。
          labels: automated
