---
# .github/workflows/validate.yaml
name: Validate Jibun OS
on:
  push:
    branches: [main, develop]
    paths: ['**.yml', '**.yaml']
  pull_request:
    paths: ['**.yml', '**.yaml']
jobs:
  lint-and-schema-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install runtime deps
        run: pip install -r requirements.txt
      - name: Install dev deps
        run: pip install -r requirements-dev.txt
      - name: Run yamllint
        run: yamllint .
      - name: Set up OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: Run OPA policy checks
        run: |
          for file in legislation/personal/projects/*.yaml; do
            echo "Checking policy for $file"
            opa eval --input "$file" \
                     --fail-defined \
                     --data policy/project_purpose_exists.rego \
                     "data.jibun_os.policy.project.deny[_]"
          done
      - name: Install PyYAML (for verify_system_map_paths.py)
        run: pip install pyyaml
      - name: Run system_map path verification
        run: python scripts/verify_system_map_paths.py
      - name: Load mappings (dry‑run)
        run: |
          python scripts/apply_mappings.py \
                 --mapping-glob "legislation/common/mappings/*.yaml"
      - name: Run yamale (Schema Validation)
        run: |-
          # check-jsonschema --schemafile schema/os_architecture.schema.json jibun_os.yml
          echo "Schema validation for modular files will be fully implemented in ci_jobs_enhancement task."
  regression-test-ai-partner:
    runs-on: ubuntu-latest
    needs: lint-and-schema-check
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run AI Partner Regression Tests
        run: pytest -v tests/test_regression.py
