---
name: Validate Jibun OS
on:
  push:
    branches: [main, develop]
    paths: ['**.yml', '**.yaml']
  pull_request:
    paths: ['**.yml', '**.yaml']
jobs:
  lint-and-schema-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install runtime deps
        run: pip install -r requirements.txt
      - name: Install dev deps
        run: pip install -r requirements-dev.txt
      - name: Run yamllint
        run: yamllint .
      - name: Run yamale (Schema Validation)
        run: |
          # check-jsonschema --schemafile schema/jibun_os.schema.json jibun_os.yml
          echo "Schema validation for modular files will be fully implemented in ci_jobs_enhancement task."
